### ISSUE TITLE
데이터가 없는 경우

### ISSUE THREAD

**Issue by JoenSooJoeng** [ClustProject/KWTDataAnalysistool#3]
조회 기간에 데이터가 없는 경우는 프로그램 실행이 되지 않나요?

**Comment by sunkyong** [comment]
데이터가 없는 경우에도 시리얼이 있으면 데이터 다운로드까지는 진행되어 파일이 생성됩니다. 다만, 해당 파일의 데이터가 비어있으므로 평균 처리 부분이 진행되지 않습니다.
